name: Security

on:
  push:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  checkov:
    name: checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v6
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@7b972723c44fb3d256283fac96fae5d7c1894bb7 # v12.3114.0
        with:
          config_file: "./configs/checkov.yml"
          directory: "."
