name: Security

on:
  push:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  checkov:
    name: checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@9c091bb21b7c1c1d1991bb908d89e4e9dddfe3e0 # v6
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@4a1afa9897f7afe297a3762c926e1e800361464f # v12.3111.0
        with:
          config_file: "./configs/checkov.yml"
          directory: "."
