name: Security

on:
  push:
  pull_request:
    branches: ["main"]

permissions:
  contents: read

jobs:
  checkov:
    name: checkov
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6
      - name: Run Checkov
        uses: bridgecrewio/checkov-action@4048c972aae68d0b983a48bb3479aab2d877b898 # v12.3102.0
        with:
          config_file: "./configs/checkov.yml"
          directory: "."
